#!/usr/bin/env zsh

TRUFFLE=~/work/truffle/packages/core/cli.js
HTTP=http://$(
  git r -v | grep origin | head -n 1 | sed 's:git@::' | sed 's:\.git::' | awk '{ print $2 }' | sed 's:\::/:'
)
COMMIT=$(git rev-parse HEAD)
GH_BASE="${HTTP}/blob/${COMMIT}/"

## clear out txns.out
rm txns.out
mkdir truffle-seq truffle-seq-short

for test in $(ls test/*); do
  md_out="truffle-seq/${test:t:r:l}.md"

  ## start ganache
  #g3
  # proc=$(tsp ganache-cli --miner.legacyInstamine  --chain.vmErrorsOnRPCResponse)
  proc=$(tsp ganache-cli --vmErrorsOnRPCResponse)

  # proc=$(tsp ganache-cli)
  #echo the ganache proc is $proc

  ## run tests
   node ${TRUFFLE} test ${test}

  ## generate
  ./gen-umls && ./gen-md.awk txns.out ${md_out} ${GH_BASE}

  ## kill ganache
  tsp -k $proc

  ## clear out txns.out
  rm txns.out
done
